return {
	CURRENCY_TYPE_DIAMOND = {
		id = "CURRENCY_TYPE_DIAMOND",
		item_id = 1
	},
	CURRENCY_TYPE_GOLD = {
		id = "CURRENCY_TYPE_GOLD",
		item_id = 2
	},
	CURRENCY_TYPE_FRIENDSHIP_POINT = {
		id = "CURRENCY_TYPE_FRIENDSHIP_POINT",
		item_id = 3
	},
	CURRENCY_TYPE_FATIGUE = {
		id = "CURRENCY_TYPE_FATIGUE",
		item_id = 4
	},
	CURRENCY_TYPE_TREASURE_TICKET = {
		id = "CURRENCY_TYPE_TREASURE_TICKET",
		item_id = 5
	},
	CURRENCY_TYPE_CHANGE_NAME_CARD = {
		id = "CURRENCY_TYPE_CHANGE_NAME_CARD",
		item_id = 6
	},
	CURRENCY_TYPE_CLUB_MEDAL = {
		id = "CURRENCY_TYPE_CLUB_MEDAL",
		item_id = 7
	},
	CURRENCY_TYPE_CLUB_POPULARITY = {
		id = "CURRENCY_TYPE_CLUB_POPULARITY",
		item_id = 8
	},
	CURRENCY_TYPE_INTELLIGENCE_POINT = {
		id = "CURRENCY_TYPE_INTELLIGENCE_POINT",
		item_id = 9
	},
	CURRENCY_TYPE_MYSTICAL_DIAMOND = {
		id = "CURRENCY_TYPE_MYSTICAL_DIAMOND",
		item_id = 10
	},
	CURRENCY_TYPE_BATTLEPASS_POINT = {
		id = "CURRENCY_TYPE_BATTLEPASS_POINT",
		item_id = 11
	},
	CURRENCY_TYPE_USER_EXP = {
		id = "CURRENCY_TYPE_USER_EXP",
		item_id = 12
	},
	CURRENCY_TYPE_HERO_EXP = {
		id = "CURRENCY_TYPE_HERO_EXP",
		item_id = 13
	},
	CURRENCY_TYPE_BATTLEPASS_EXP = {
		id = "CURRENCY_TYPE_BATTLEPASS_EXP",
		item_id = 14
	},
	CURRENCY_TYPE_INFO_BADGE_LOW = {
		id = "CURRENCY_TYPE_INFO_BADGE_LOW",
		item_id = 15
	},
	CURRENCY_TYPE_INFO_BADGE_MID = {
		id = "CURRENCY_TYPE_INFO_BADGE_MID",
		item_id = 40901
	},
	CURRENCY_TYPE_INFO_BADGE_TOP = {
		id = "CURRENCY_TYPE_INFO_BADGE_TOP",
		item_id = 40902
	},
	CURRENCY_TYPE_RECALL_CHAPTER = {
		id = "CURRENCY_TYPE_RECALL_CHAPTER",
		item_id = 18
	},
	CURRENCY_TYPE_TREASURE_TICKET_EQUIP = {
		id = "CURRENCY_TYPE_TREASURE_TICKET_EQUIP",
		item_id = 19
	},
	CURRENCY_TYPE_FIVE_STAR_EQUIP_RESOLVE = {
		id = "CURRENCY_TYPE_FIVE_STAR_EQUIP_RESOLVE",
		item_id = 41001
	},
	CURRENCY_TYPE_SIX_STAR_EQUIP_RESOLVE = {
		id = "CURRENCY_TYPE_SIX_STAR_EQUIP_RESOLVE",
		item_id = 41002
	},
	CURRENCY_TYPE_DAILY_ACTIVITY_PT = {
		id = "CURRENCY_TYPE_DAILY_ACTIVITY_PT",
		item_id = 22
	},
	CURRENCY_TYPE_NEW_ACTIVITY_PT = {
		id = "CURRENCY_TYPE_NEW_ACTIVITY_PT",
		item_id = 23
	},
	CURRENCY_TYPE_SKIN = {
		id = "CURRENCY_TYPE_SKIN",
		item_id = 24
	},
	CURRENCY_TYPE_MYTHIC = {
		id = "CURRENCY_TYPE_MYTHIC",
		item_id = 25
	},
	CURRENCY_TYPE_MATRIX_COIN = {
		id = "CURRENCY_TYPE_MATRIX_COIN",
		item_id = 26
	},
	CURRENCY_TYPE_MATRIX_RING = {
		id = "CURRENCY_TYPE_MATRIX_RING",
		item_id = 27
	},
	CURRENCY_TYPE_MATRIX_CERTIFICATION = {
		id = "CURRENCY_TYPE_MATRIX_CERTIFICATION",
		item_id = 28
	},
	CURRENCY_TYPE_MATRIX_PT = {
		id = "CURRENCY_TYPE_MATRIX_PT",
		item_id = 29
	},
	CURRENCY_TYPE_RECHARGE_DIAMOND_IOS = {
		id = "CURRENCY_TYPE_RECHARGE_DIAMOND_IOS",
		item_id = 30
	},
	CURRENCY_TYPE_RECHARGE_DIAMOND_NOT_IOS = {
		id = "CURRENCY_TYPE_RECHARGE_DIAMOND_NOT_IOS",
		item_id = 31
	},
	CURRENCY_TYPE_RECHARGE_DIAMOND_FREE = {
		id = "CURRENCY_TYPE_RECHARGE_DIAMOND_FREE",
		item_id = 32
	},
	CURRENCY_TYPE_ACHIEVEMENT_POINT = {
		id = "CURRENCY_TYPE_ACHIEVEMENT_POINT",
		item_id = 33
	},
	CURRENCY_TYPE_MATRIX_TERMINAL_EXP = {
		id = "CURRENCY_TYPE_MATRIX_TERMINAL_EXP",
		item_id = 34
	},
	CURRENCY_TYPE_WEEK_ACTIVITY_PT = {
		id = "CURRENCY_TYPE_WEEK_ACTIVITY_PT",
		item_id = 35
	},
	CURRENCY_TYPE_DRAW = {
		id = "CURRENCY_TYPE_DRAW",
		item_id = 36
	},
	CURRENCY_TYPE_BOSS_CHALLENGE = {
		id = "CURRENCY_TYPE_BOSS_CHALLENGE",
		item_id = 37
	},
	CURRENCY_TYPE_TREASURE_TICKET_ACTIVITY = {
		id = "CURRENCY_TYPE_TREASURE_TICKET_ACTIVITY",
		item_id = 38
	},
	CURRENCY_TYPE_DORM_GOLD = {
		id = "CURRENCY_TYPE_DORM_GOLD",
		item_id = 39
	},
	CURRENCY_TYPE_CLUB_COIN_A = {
		id = "CURRENCY_TYPE_CLUB_COIN_A",
		item_id = 52001
	},
	CURRENCY_TYPE_CLUB_COIN_B = {
		id = "CURRENCY_TYPE_CLUB_COIN_B",
		item_id = 40
	},
	CURRENCY_TYPE_BOSS_CHALLENGE_S = {
		id = "CURRENCY_TYPE_BOSS_CHALLENGE_S",
		item_id = 41
	},
	CURRENCY_TYPE_OSIRIS_INFINITY_COIN = {
		id = "CURRENCY_TYPE_OSIRIS_INFINITY_COIN",
		item_id = 53001
	},
	CURRENCY_TYPE_HELLA_TALENT_TREE_COIN = {
		id = "CURRENCY_TYPE_HELLA_TALENT_TREE_COIN",
		item_id = 54001
	},
	CURRENCY_TYPE_HELLA_SHOP_COIN = {
		id = "CURRENCY_TYPE_HELLA_SHOP_COIN",
		item_id = 54002
	},
	CURRENCY_TYPE_SUMMER_FISHING_COIN = {
		id = "CURRENCY_TYPE_SUMMER_FISHING_COIN",
		item_id = 54003
	},
	CURRENCY_TYPE_RETURN_COIN = {
		id = "CURRENCY_TYPE_RETURN_COIN",
		item_id = 54004
	},
	CURRENCY_TYPE_SUMMER_SKIN_COIN = {
		id = "CURRENCY_TYPE_SUMMER_SKIN_COIN",
		item_id = 54005
	},
	CURRENCY_TYPE_SUMMER_PT = {
		id = "CURRENCY_TYPE_SUMMER_PT",
		item_id = 54006
	},
	CURRENCY_TYPE_BOSS_CHALLENGE_ADVANCE = {
		id = "CURRENCY_TYPE_BOSS_CHALLENGE_ADVANCE",
		item_id = 42
	},
	CURRENCY_TYPE_CHAPTERIII_PT = {
		id = "CURRENCY_TYPE_CHAPTERIII_PT",
		item_id = 53003
	},
	CURRENCY_TYPE_ACTIVITY_RACE = {
		id = "CURRENCY_TYPE_ACTIVITY_RACE",
		item_id = 53006
	},
	CURRENCY_TYPE_CHAPTERIII_DOWN_PT = {
		id = "CURRENCY_TYPE_CHAPTERIII_DOWN_PT",
		item_id = 53007
	},
	CURRENCY_TYPE_ACTIVITY_CLUB_BOSS_MAP_COIN = {
		id = "CURRENCY_TYPE_ACTIVITY_CLUB_BOSS_MAP_COIN",
		item_id = 53008
	},
	CURRENCY_TYPE_FINAL_MYTHIC = {
		id = "CURRENCY_TYPE_FINAL_MYTHIC",
		item_id = 43
	},
	CURRENCY_TYPE_FACTORY_INFINITY_COIN = {
		id = "CURRENCY_TYPE_FACTORY_INFINITY_COIN",
		item_id = 53010
	},
	CURRENCY_TYPE_FACTORY_PT = {
		id = "CURRENCY_TYPE_FACTORY_PT",
		item_id = 53011
	},
	CURRENCY_TYPE_FESTIVAL_MONSTER_PT = {
		id = "CURRENCY_TYPE_FESTIVAL_MONSTER_PT",
		item_id = 53012
	},
	CURRENCY_TYPE_EMPTYDREAM_PT = {
		id = "CURRENCY_TYPE_EMPTYDREAM_PT",
		item_id = 53013
	},
	CURRENCY_TYPE_PASS_SENIOR_COIN = {
		id = "CURRENCY_TYPE_PASS_SENIOR_COIN",
		item_id = 53014
	},
	CURRENCY_TYPE_PASS_LOWER_COIN = {
		id = "CURRENCY_TYPE_PASS_LOWER_COIN",
		item_id = 53015
	},
	CURRENCY_TYPE_FESTIVAL_CANTEEN_COIN = {
		id = "CURRENCY_TYPE_FESTIVAL_CANTEEN_COIN",
		item_id = 54013
	},
	CURRENCY_TYPE_TYR_COIN = {
		id = "CURRENCY_TYPE_TYR_COIN",
		item_id = 53016
	},
	CURRENCY_XUHENG_COIN = {
		id = "CURRENCY_XUHENG_COIN",
		item_id = 53017
	},
	CURRENCY_XUHENG_TICKET = {
		id = "CURRENCY_XUHENG_TICKET",
		item_id = 54014
	},
	CURRENCY_XUHENG_CULTIVATE_COIN = {
		id = "CURRENCY_XUHENG_CULTIVATE_COIN",
		item_id = 54015
	},
	CURRENCY_TYPE_NEW_RETURN_COIN = {
		id = "CURRENCY_TYPE_NEW_RETURN_COIN",
		item_id = 54016
	},
	CURRENCY_TYPE_RECALLED_COIN = {
		id = "CURRENCY_TYPE_RECALLED_COIN",
		item_id = 53021
	},
	CURRENCY_TYPE_DRAW_FEEDBACK_COIN = {
		id = "CURRENCY_TYPE_DRAW_FEEDBACK_COIN",
		item_id = 53022
	},
	CURRENCY_TYPE_UNLOCK_PROPS = {
		id = "CURRENCY_TYPE_UNLOCK_PROPS",
		item_id = 44
	},
	CURRENCY_TYPE_SHIFTING_EXP = {
		id = "CURRENCY_TYPE_SHIFTING_EXP",
		item_id = 45
	},
	CURRENCY_TYPE_WEAPON_MODULE = {
		id = "CURRENCY_TYPE_WEAPON_MODULE",
		item_id = 41601
	},
	CURRENCY_TYPE_POLYHEDRON_TERMINAL_EXP = {
		id = "CURRENCY_TYPE_POLYHEDRON_TERMINAL_EXP",
		item_id = 46
	},
	all = {
		CURRENCY_TYPE_DIAMOND,
		CURRENCY_TYPE_GOLD,
		CURRENCY_TYPE_FRIENDSHIP_POINT,
		CURRENCY_TYPE_FATIGUE,
		CURRENCY_TYPE_TREASURE_TICKET,
		CURRENCY_TYPE_CHANGE_NAME_CARD,
		CURRENCY_TYPE_CLUB_MEDAL,
		CURRENCY_TYPE_CLUB_POPULARITY,
		CURRENCY_TYPE_INTELLIGENCE_POINT,
		CURRENCY_TYPE_MYSTICAL_DIAMOND,
		CURRENCY_TYPE_BATTLEPASS_POINT,
		CURRENCY_TYPE_USER_EXP,
		CURRENCY_TYPE_HERO_EXP,
		CURRENCY_TYPE_BATTLEPASS_EXP,
		CURRENCY_TYPE_INFO_BADGE_LOW,
		CURRENCY_TYPE_INFO_BADGE_MID,
		CURRENCY_TYPE_INFO_BADGE_TOP,
		CURRENCY_TYPE_RECALL_CHAPTER,
		CURRENCY_TYPE_TREASURE_TICKET_EQUIP,
		CURRENCY_TYPE_FIVE_STAR_EQUIP_RESOLVE,
		CURRENCY_TYPE_SIX_STAR_EQUIP_RESOLVE,
		CURRENCY_TYPE_DAILY_ACTIVITY_PT,
		CURRENCY_TYPE_NEW_ACTIVITY_PT,
		CURRENCY_TYPE_SKIN,
		CURRENCY_TYPE_MYTHIC,
		CURRENCY_TYPE_MATRIX_COIN,
		CURRENCY_TYPE_MATRIX_RING,
		CURRENCY_TYPE_MATRIX_CERTIFICATION,
		CURRENCY_TYPE_MATRIX_PT,
		CURRENCY_TYPE_RECHARGE_DIAMOND_IOS,
		CURRENCY_TYPE_RECHARGE_DIAMOND_NOT_IOS,
		CURRENCY_TYPE_RECHARGE_DIAMOND_FREE,
		CURRENCY_TYPE_ACHIEVEMENT_POINT,
		CURRENCY_TYPE_MATRIX_TERMINAL_EXP,
		CURRENCY_TYPE_WEEK_ACTIVITY_PT,
		CURRENCY_TYPE_DRAW,
		CURRENCY_TYPE_BOSS_CHALLENGE,
		CURRENCY_TYPE_TREASURE_TICKET_ACTIVITY,
		CURRENCY_TYPE_DORM_GOLD,
		CURRENCY_TYPE_CLUB_COIN_A,
		CURRENCY_TYPE_CLUB_COIN_B,
		CURRENCY_TYPE_BOSS_CHALLENGE_S,
		CURRENCY_TYPE_OSIRIS_INFINITY_COIN,
		CURRENCY_TYPE_HELLA_TALENT_TREE_COIN,
		CURRENCY_TYPE_HELLA_SHOP_COIN,
		CURRENCY_TYPE_SUMMER_FISHING_COIN,
		CURRENCY_TYPE_RETURN_COIN,
		CURRENCY_TYPE_SUMMER_SKIN_COIN,
		CURRENCY_TYPE_SUMMER_PT,
		CURRENCY_TYPE_BOSS_CHALLENGE_ADVANCE,
		CURRENCY_TYPE_CHAPTERIII_PT,
		CURRENCY_TYPE_ACTIVITY_RACE,
		CURRENCY_TYPE_CHAPTERIII_DOWN_PT,
		CURRENCY_TYPE_ACTIVITY_CLUB_BOSS_MAP_COIN,
		CURRENCY_TYPE_FINAL_MYTHIC,
		CURRENCY_TYPE_FACTORY_INFINITY_COIN,
		CURRENCY_TYPE_FACTORY_PT,
		CURRENCY_TYPE_FESTIVAL_MONSTER_PT,
		CURRENCY_TYPE_EMPTYDREAM_PT,
		CURRENCY_TYPE_PASS_SENIOR_COIN,
		CURRENCY_TYPE_PASS_LOWER_COIN,
		CURRENCY_TYPE_FESTIVAL_CANTEEN_COIN,
		CURRENCY_TYPE_TYR_COIN,
		CURRENCY_XUHENG_COIN,
		CURRENCY_XUHENG_TICKET,
		CURRENCY_XUHENG_CULTIVATE_COIN,
		CURRENCY_TYPE_NEW_RETURN_COIN,
		CURRENCY_TYPE_RECALLED_COIN,
		CURRENCY_TYPE_DRAW_FEEDBACK_COIN,
		CURRENCY_TYPE_UNLOCK_PROPS,
		CURRENCY_TYPE_SHIFTING_EXP,
		CURRENCY_TYPE_WEAPON_MODULE,
		CURRENCY_TYPE_POLYHEDRON_TERMINAL_EXP
	}
}
