return {
	GAME_POLYHEDRON_ATTRIBUTE_LEADER_REBORN_TIMES = {
		enum = "GAME_POLYHEDRON_ATTRIBUTE_LEADER_REBORN_TIMES",
		id = 1
	},
	GAME_POLYHEDRON_ATTRIBUTE_REBORN_HEALTH_PERCENT = {
		enum = "GAME_POLYHEDRON_ATTRIBUTE_REBORN_HEALTH_PERCENT",
		id = 2
	},
	GAME_POLYHEDRON_ATTRIBUTE_TEAMMATE_REBORN_MAX_COLD_DOWN = {
		enum = "GAME_POLYHEDRON_ATTRIBUTE_TEAMMATE_REBORN_MAX_COLD_DOWN",
		id = 3
	},
	GAME_POLYHEDRON_ATTRIBUTE_EXTRA_CHALLENGE_PICK_UP = {
		enum = "GAME_POLYHEDRON_ATTRIBUTE_EXTRA_CHALLENGE_PICK_UP",
		id = 4
	},
	GAME_POLYHEDRON_ATTRIBUTE_ARTIFACT_MAX_LEVEL = {
		enum = "GAME_POLYHEDRON_ATTRIBUTE_ARTIFACT_MAX_LEVEL",
		id = 5
	},
	GAME_POLYHEDRON_ATTRIBUTE_ARTIFACT_BONUS_LEVEL_PERCENT = {
		enum = "GAME_POLYHEDRON_ATTRIBUTE_ARTIFACT_BONUS_LEVEL_PERCENT",
		id = 6
	},
	GAME_POLYHEDRON_ATTRIBUTE_RE_ROLL_GATE_TIMES = {
		enum = "GAME_POLYHEDRON_ATTRIBUTE_RE_ROLL_GATE_TIMES",
		id = 7
	},
	GAME_POLYHEDRON_ATTRIBUTE_RE_ROLL_ARTIFACT_REWARD_TIMES = {
		enum = "GAME_POLYHEDRON_ATTRIBUTE_RE_ROLL_ARTIFACT_REWARD_TIMES",
		id = 8
	},
	GAME_POLYHEDRON_ATTRIBUTE_CURRENCY_BONUS = {
		enum = "GAME_POLYHEDRON_ATTRIBUTE_CURRENCY_BONUS",
		id = 9
	},
	GAME_POLYHEDRON_ATTRIBUTE_HERO_ATTRIBUTE_BONUS_COLD_DOWN = {
		enum = "GAME_POLYHEDRON_ATTRIBUTE_HERO_ATTRIBUTE_BONUS_COLD_DOWN",
		id = 10
	},
	GAME_POLYHEDRON_ATTRIBUTE_HERO_ATTRIBUTE_BONUS_MAX_COLD_DOWN = {
		enum = "GAME_POLYHEDRON_ATTRIBUTE_HERO_ATTRIBUTE_BONUS_MAX_COLD_DOWN",
		id = 11
	},
	GAME_POLYHEDRON_ATTRIBUTE_ARTIFACT_LEVEL_BONUS_COLD_DOWN = {
		enum = "GAME_POLYHEDRON_ATTRIBUTE_ARTIFACT_LEVEL_BONUS_COLD_DOWN",
		id = 12
	},
	GAME_POLYHEDRON_ATTRIBUTE_ARTIFACT_LEVEL_BONUS_MAX_COLD_DOWN = {
		enum = "GAME_POLYHEDRON_ATTRIBUTE_ARTIFACT_LEVEL_BONUS_MAX_COLD_DOWN",
		id = 13
	},
	GAME_POLYHEDRON_ATTRIBUTE_HERO_ATTRIBUTE_REWARD_EFFECT_ID_LIST_INDEX = {
		enum = "GAME_POLYHEDRON_ATTRIBUTE_HERO_ATTRIBUTE_REWARD_EFFECT_ID_LIST_INDEX",
		id = 14
	},
	GAME_POLYHEDRON_ATTRIBUTE_SHOP_ITEM_NUM = {
		enum = "GAME_POLYHEDRON_ATTRIBUTE_SHOP_ITEM_NUM",
		id = 15
	},
	GAME_POLYHEDRON_ATTRIBUTE_SHOP_REFRESH_TIME = {
		enum = "GAME_POLYHEDRON_ATTRIBUTE_SHOP_REFRESH_TIME",
		id = 16
	},
	GAME_POLYHEDRON_ATTRIBUTE_SHOP_RECOVER_TIME = {
		enum = "GAME_POLYHEDRON_ATTRIBUTE_SHOP_RECOVER_TIME",
		id = 17
	},
	GAME_POLYHEDRON_ATTRIBUTE_SHOP_FREE_REFRESH_TIME = {
		enum = "GAME_POLYHEDRON_ATTRIBUTE_SHOP_FREE_REFRESH_TIME",
		id = 18
	},
	GAME_POLYHEDRON_ATTRIBUTE_BOSS_EVENT_AFTER_EVENT_COIN_MULTIPLE_RATE = {
		enum = "GAME_POLYHEDRON_ATTRIBUTE_BOSS_EVENT_AFTER_EVENT_COIN_MULTIPLE_RATE",
		id = 19
	},
	GAME_POLYHEDRON_ATTRIBUTE_BOSS_EVENT_AFTER_EVENT_ADD_REBORN_TIMES = {
		enum = "GAME_POLYHEDRON_ATTRIBUTE_BOSS_EVENT_AFTER_EVENT_ADD_REBORN_TIMES",
		id = 20
	},
	GAME_POLYHEDRON_ATTRIBUTE_BOSS_EVENT_AFTER_EVENT_ARTIFACT_STRENGTH_RATE = {
		enum = "GAME_POLYHEDRON_ATTRIBUTE_BOSS_EVENT_AFTER_EVENT_ARTIFACT_STRENGTH_RATE",
		id = 21
	},
	GAME_POLYHEDRON_ATTRIBUTE_FIRST_EVENT_INDEX = {
		enum = "GAME_POLYHEDRON_ATTRIBUTE_FIRST_EVENT_INDEX",
		id = 22
	},
	GAME_POLYHEDRON_ATTRIBUTE_ARTIFACT_EXTRA_SUB_TYPE_INDEX = {
		enum = "GAME_POLYHEDRON_ATTRIBUTE_ARTIFACT_EXTRA_SUB_TYPE_INDEX",
		id = 23
	},
	GAME_POLYHEDRON_ATTRIBUTE_EXTRA_ELITE_PICK_UP = {
		enum = "GAME_POLYHEDRON_ATTRIBUTE_EXTRA_ELITE_PICK_UP",
		id = 24
	},
	GAME_POLYHEDRON_ATTRIBUTE_BOSS_EVENT_EXTRA_PARAMS = {
		enum = "GAME_POLYHEDRON_ATTRIBUTE_BOSS_EVENT_EXTRA_PARAMS",
		id = 25
	},
	GAME_POLYHEDRON_ATTRIBUTE_AFTER_EVENT_COIN_BONUS = {
		enum = "GAME_POLYHEDRON_ATTRIBUTE_AFTER_EVENT_COIN_BONUS",
		id = 26
	},
	GAME_POLYHEDRON_ATTRIBUTE_AFTER_EVENT_HP_RECOVER = {
		enum = "GAME_POLYHEDRON_ATTRIBUTE_AFTER_EVENT_HP_RECOVER",
		id = 27
	},
	GAME_POLYHEDRON_ATTRIBUTE_GIVE_UP_ADD_COIN_NUM = {
		enum = "GAME_POLYHEDRON_ATTRIBUTE_GIVE_UP_ADD_COIN_NUM",
		id = 28
	},
	GAME_POLYHEDRON_ATTRIBUTE_FIRST_SHOP_ITEM_DISCOUNT = {
		enum = "GAME_POLYHEDRON_ATTRIBUTE_FIRST_SHOP_ITEM_DISCOUNT",
		id = 29
	},
	GAME_POLYHEDRON_ATTRIBUTE_LEADER_REBORN_MAX_TIMES = {
		enum = "GAME_POLYHEDRON_ATTRIBUTE_LEADER_REBORN_MAX_TIMES",
		id = 30
	},
	GAME_POLYHEDRON_ATTRIBUTE_EXTRA_ARTIFACT_STRENGTH_REWARD_RATE = {
		enum = "GAME_POLYHEDRON_ATTRIBUTE_EXTRA_ARTIFACT_STRENGTH_REWARD_RATE",
		id = 31
	},
	GAME_POLYHEDRON_ATTRIBUTE_EXTRA_TEAMMATE_EVENT_RATE = {
		enum = "GAME_POLYHEDRON_ATTRIBUTE_EXTRA_TEAMMATE_EVENT_RATE",
		id = 32
	},
	GAME_POLYHEDRON_ATTRIBTUE_EXTRA_EXP_RATE = {
		enum = "GAME_POLYHEDRON_ATTRIBTUE_EXTRA_EXP_RATE",
		id = 33
	},
	GAME_POLYHEDRON_ATTRIBUTE_TIER_ONE_BONUS_GATE_NUM = {
		enum = "GAME_POLYHEDRON_ATTRIBUTE_TIER_ONE_BONUS_GATE_NUM",
		id = 34
	},
	all = {
		GAME_POLYHEDRON_ATTRIBUTE_LEADER_REBORN_TIMES,
		GAME_POLYHEDRON_ATTRIBUTE_REBORN_HEALTH_PERCENT,
		GAME_POLYHEDRON_ATTRIBUTE_TEAMMATE_REBORN_MAX_COLD_DOWN,
		GAME_POLYHEDRON_ATTRIBUTE_EXTRA_CHALLENGE_PICK_UP,
		GAME_POLYHEDRON_ATTRIBUTE_ARTIFACT_MAX_LEVEL,
		GAME_POLYHEDRON_ATTRIBUTE_ARTIFACT_BONUS_LEVEL_PERCENT,
		GAME_POLYHEDRON_ATTRIBUTE_RE_ROLL_GATE_TIMES,
		GAME_POLYHEDRON_ATTRIBUTE_RE_ROLL_ARTIFACT_REWARD_TIMES,
		GAME_POLYHEDRON_ATTRIBUTE_CURRENCY_BONUS,
		GAME_POLYHEDRON_ATTRIBUTE_HERO_ATTRIBUTE_BONUS_COLD_DOWN,
		GAME_POLYHEDRON_ATTRIBUTE_HERO_ATTRIBUTE_BONUS_MAX_COLD_DOWN,
		GAME_POLYHEDRON_ATTRIBUTE_ARTIFACT_LEVEL_BONUS_COLD_DOWN,
		GAME_POLYHEDRON_ATTRIBUTE_ARTIFACT_LEVEL_BONUS_MAX_COLD_DOWN,
		GAME_POLYHEDRON_ATTRIBUTE_HERO_ATTRIBUTE_REWARD_EFFECT_ID_LIST_INDEX,
		GAME_POLYHEDRON_ATTRIBUTE_SHOP_ITEM_NUM,
		GAME_POLYHEDRON_ATTRIBUTE_SHOP_REFRESH_TIME,
		GAME_POLYHEDRON_ATTRIBUTE_SHOP_RECOVER_TIME,
		GAME_POLYHEDRON_ATTRIBUTE_SHOP_FREE_REFRESH_TIME,
		GAME_POLYHEDRON_ATTRIBUTE_BOSS_EVENT_AFTER_EVENT_COIN_MULTIPLE_RATE,
		GAME_POLYHEDRON_ATTRIBUTE_BOSS_EVENT_AFTER_EVENT_ADD_REBORN_TIMES,
		GAME_POLYHEDRON_ATTRIBUTE_BOSS_EVENT_AFTER_EVENT_ARTIFACT_STRENGTH_RATE,
		GAME_POLYHEDRON_ATTRIBUTE_FIRST_EVENT_INDEX,
		GAME_POLYHEDRON_ATTRIBUTE_ARTIFACT_EXTRA_SUB_TYPE_INDEX,
		GAME_POLYHEDRON_ATTRIBUTE_EXTRA_ELITE_PICK_UP,
		GAME_POLYHEDRON_ATTRIBUTE_BOSS_EVENT_EXTRA_PARAMS,
		GAME_POLYHEDRON_ATTRIBUTE_AFTER_EVENT_COIN_BONUS,
		GAME_POLYHEDRON_ATTRIBUTE_AFTER_EVENT_HP_RECOVER,
		GAME_POLYHEDRON_ATTRIBUTE_GIVE_UP_ADD_COIN_NUM,
		GAME_POLYHEDRON_ATTRIBUTE_FIRST_SHOP_ITEM_DISCOUNT,
		GAME_POLYHEDRON_ATTRIBUTE_LEADER_REBORN_MAX_TIMES,
		GAME_POLYHEDRON_ATTRIBUTE_EXTRA_ARTIFACT_STRENGTH_REWARD_RATE,
		GAME_POLYHEDRON_ATTRIBUTE_EXTRA_TEAMMATE_EVENT_RATE,
		GAME_POLYHEDRON_ATTRIBTUE_EXTRA_EXP_RATE,
		GAME_POLYHEDRON_ATTRIBUTE_TIER_ONE_BONUS_GATE_NUM
	}
}
