return {
	[2] = {
		refresh_num_limit = 0,
		initiative_refresh = 0,
		group_name = "情报兑换",
		type = 3,
		system = "shop",
		show_in_shop = 1,
		chain_last_visible = 0,
		display_index = 1,
		activity_id = 0,
		remark = "情报兑换",
		params = "",
		id = 2,
		display_group = 4,
		operation_stop_id = 816,
		cost_id = {
			40901,
			40902
		}
	},
	[3] = {
		refresh_num_limit = 0,
		initiative_refresh = 0,
		group_name = "凭证置换",
		type = 3,
		system = "shop",
		show_in_shop = 1,
		chain_last_visible = 0,
		display_index = 1,
		activity_id = 0,
		remark = "黑区净化",
		id = 3,
		display_group = 5,
		operation_stop_id = 817,
		cost_id = {
			"CURRENCY_TYPE_MYTHIC",
			"CURRENCY_TYPE_FINAL_MYTHIC"
		},
		params = {
			{
				SUIT_ALL_LABEL = "ALL_GOODS",
				POS_ALL_LABEL = "ALL_GOODS"
			}
		}
	},
	[5] = {
		refresh_num_limit = 0,
		initiative_refresh = 0,
		group_name = "刻印研发",
		type = 3,
		system = "shop",
		show_in_shop = 1,
		chain_last_visible = 0,
		display_index = 3,
		activity_id = 0,
		remark = "五星刻印",
		params = "",
		id = 5,
		display_group = 3,
		operation_stop_id = 814,
		cost_id = {
			41002
		}
	},
	[6] = {
		refresh_num_limit = 0,
		initiative_refresh = 0,
		group_name = "刻印研发",
		type = 3,
		system = "shop",
		show_in_shop = 1,
		chain_last_visible = 0,
		display_index = 4,
		activity_id = 0,
		remark = "启示录",
		params = "",
		id = 6,
		display_group = 3,
		operation_stop_id = 815,
		cost_id = {
			41001,
			41002
		}
	},
	[7] = {
		refresh_num_limit = 0,
		initiative_refresh = 0,
		group_name = "物资采购",
		type = 1,
		system = "shop",
		show_in_shop = 1,
		chain_last_visible = 0,
		display_index = 1,
		activity_id = 0,
		remark = "物资采购",
		params = "",
		id = 7,
		display_group = 1,
		operation_stop_id = 810,
		cost_id = {
			"CURRENCY_TYPE_GOLD",
			"CURRENCY_TYPE_DIAMOND"
		}
	},
	[8] = {
		refresh_num_limit = 20,
		initiative_refresh = 1,
		group_name = "限时特供",
		type = 1,
		system = "shop",
		show_in_shop = 1,
		chain_last_visible = 0,
		display_index = 1,
		activity_id = 0,
		remark = "限时特供",
		params = "",
		id = 8,
		display_group = 2,
		operation_stop_id = 811,
		cost_id = {
			"CURRENCY_TYPE_GOLD",
			"CURRENCY_TYPE_DIAMOND"
		}
	},
	[11] = {
		refresh_num_limit = 0,
		initiative_refresh = 0,
		group_name = "刻印研发",
		type = 3,
		system = "shop",
		show_in_shop = 1,
		chain_last_visible = 0,
		display_index = 1,
		activity_id = 0,
		remark = "三星刻印",
		params = "",
		id = 11,
		display_group = 3,
		operation_stop_id = 812,
		cost_id = {
			41001
		}
	},
	[12] = {
		refresh_num_limit = 0,
		initiative_refresh = 0,
		group_name = "刻印研发",
		type = 3,
		system = "shop",
		show_in_shop = 1,
		chain_last_visible = 0,
		display_index = 2,
		activity_id = 0,
		remark = "四星刻印",
		params = "",
		id = 12,
		display_group = 3,
		operation_stop_id = 813,
		cost_id = {
			41001
		}
	},
	[14] = {
		refresh_num_limit = 0,
		initiative_refresh = 0,
		group_name = "",
		type = 2,
		system = "recharge",
		show_in_shop = 0,
		chain_last_visible = 0,
		display_index = 1,
		activity_id = 0,
		remark = "皮肤商店（充值）",
		params = "",
		id = 14,
		display_group = 1,
		operation_stop_id = 807,
		cost_id = {}
	},
	[15] = {
		refresh_num_limit = 0,
		initiative_refresh = 0,
		group_name = "",
		type = 2,
		system = "recharge",
		show_in_shop = 0,
		chain_last_visible = 0,
		display_index = 1,
		activity_id = 0,
		remark = "限时补给",
		params = "",
		id = 15,
		display_group = 1,
		operation_stop_id = 805,
		cost_id = {}
	},
	[16] = {
		refresh_num_limit = 0,
		initiative_refresh = 0,
		group_name = "",
		type = 1,
		system = "recharge",
		show_in_shop = 0,
		chain_last_visible = 0,
		display_index = 1,
		activity_id = 0,
		remark = "周期商店",
		params = "",
		id = 16,
		display_group = 1,
		operation_stop_id = 0,
		cost_id = {}
	},
	[17] = {
		refresh_num_limit = 0,
		initiative_refresh = 0,
		group_name = "凭证置换",
		type = 3,
		system = "shop",
		show_in_shop = 1,
		chain_last_visible = 0,
		display_index = 3,
		activity_id = 0,
		remark = "梦境再构",
		params = "",
		id = 17,
		display_group = 5,
		operation_stop_id = 819,
		cost_id = {
			"CURRENCY_TYPE_BOSS_CHALLENGE",
			"CURRENCY_TYPE_BOSS_CHALLENGE_S",
			"CURRENCY_TYPE_BOSS_CHALLENGE_ADVANCE"
		}
	},
	[18] = {
		refresh_num_limit = 0,
		initiative_refresh = 0,
		group_name = "",
		type = 3,
		system = "recharge",
		show_in_shop = 0,
		chain_last_visible = 0,
		display_index = 0,
		activity_id = 0,
		remark = "凭证兑换",
		params = "",
		id = 18,
		display_group = 1,
		operation_stop_id = 808,
		cost_id = {}
	},
	[19] = {
		refresh_num_limit = 0,
		initiative_refresh = 0,
		group_name = "交易中心",
		type = 1,
		system = "shop",
		show_in_shop = 1,
		chain_last_visible = 0,
		display_index = 2,
		activity_id = 0,
		remark = "辉芒商店",
		params = "",
		id = 19,
		display_group = 6,
		operation_stop_id = 820,
		cost_id = {
			"CURRENCY_TYPE_DRAW"
		}
	},
	[34] = {
		refresh_num_limit = 0,
		initiative_refresh = 0,
		group_name = "交易中心",
		type = 1,
		system = "shop",
		show_in_shop = 1,
		chain_last_visible = 0,
		display_index = 3,
		activity_id = 0,
		remark = "合作商店",
		params = "",
		id = 34,
		display_group = 6,
		operation_stop_id = 832,
		cost_id = {
			53014,
			53015
		}
	},
	[20] = {
		refresh_num_limit = 0,
		initiative_refresh = 0,
		group_name = "游园商店",
		type = 1,
		system = "shop",
		show_in_shop = 0,
		chain_last_visible = 0,
		display_index = 1,
		activity_id = 0,
		remark = "游园商店",
		params = "",
		id = 20,
		display_group = 7,
		operation_stop_id = 835,
		cost_id = {
			"CURRENCY_TYPE_DORM_GOLD",
			"CURRENCY_TYPE_DIAMOND"
		}
	},
	[21] = {
		refresh_num_limit = 0,
		initiative_refresh = 0,
		group_name = "矩阵供应",
		type = 1,
		system = "shop",
		show_in_shop = 1,
		chain_last_visible = 0,
		display_index = 1,
		activity_id = 0,
		remark = "矩阵供应",
		params = "",
		id = 21,
		display_group = 6,
		operation_stop_id = 821,
		cost_id = {
			"CURRENCY_TYPE_CLUB_COIN_B"
		}
	},
	[22] = {
		refresh_num_limit = 0,
		initiative_refresh = 0,
		group_name = "",
		type = 2,
		system = "recharge",
		show_in_shop = 0,
		chain_last_visible = 0,
		display_index = 1,
		activity_id = 0,
		remark = "新手补给",
		params = "",
		id = 22,
		display_group = 1,
		operation_stop_id = 804,
		cost_id = {}
	},
	[23] = {
		refresh_num_limit = 0,
		initiative_refresh = 0,
		group_name = "",
		type = 2,
		system = "recharge",
		show_in_shop = 0,
		chain_last_visible = 0,
		display_index = 1,
		activity_id = 0,
		remark = "日常补给",
		params = "",
		id = 23,
		display_group = 1,
		operation_stop_id = 806,
		cost_id = {}
	},
	[24] = {
		refresh_num_limit = 0,
		initiative_refresh = 0,
		group_name = "物资兑换所",
		type = 3,
		system = "shop",
		show_in_shop = 0,
		chain_last_visible = 0,
		display_index = 4,
		activity_id = 0,
		remark = "物资兑换所",
		params = "",
		id = 24,
		display_group = 9,
		operation_stop_id = 822,
		cost_id = {
			"CURRENCY_TYPE_HELLA_SHOP_COIN"
		}
	},
	[25] = {
		refresh_num_limit = 0,
		initiative_refresh = 0,
		group_name = "置换中心",
		type = 4,
		system = "shop",
		show_in_shop = 0,
		chain_last_visible = 0,
		display_index = 1,
		activity_id = 0,
		remark = "数据置换",
		params = "",
		id = 25,
		display_group = 10,
		operation_stop_id = 823,
		cost_id = {
			"CURRENCY_TYPE_RECHARGE_DIAMOND_FREE"
		}
	},
	[26] = {
		refresh_num_limit = 0,
		initiative_refresh = 0,
		group_name = "异能置换机",
		type = 3,
		system = "shop",
		show_in_shop = 0,
		chain_last_visible = 0,
		display_index = 1,
		activity_id = 0,
		remark = "异能置换机",
		params = "",
		id = 26,
		display_group = 10,
		operation_stop_id = 824,
		cost_id = {
			"CURRENCY_TYPE_SUMMER_PT"
		}
	},
	[27] = {
		refresh_num_limit = 0,
		initiative_refresh = 0,
		group_name = "藏品鉴定所",
		type = 3,
		system = "shop",
		show_in_shop = 0,
		chain_last_visible = 0,
		display_index = 1,
		activity_id = 81461,
		remark = "藏品鉴定所",
		params = "",
		id = 27,
		display_group = 10,
		operation_stop_id = 825,
		cost_id = {
			53003
		}
	},
	[28] = {
		refresh_num_limit = 0,
		initiative_refresh = 0,
		group_name = "降析解构",
		type = 3,
		system = "shop",
		show_in_shop = 1,
		chain_last_visible = 0,
		display_index = 1,
		activity_id = 0,
		remark = "降析解构",
		params = "",
		id = 28,
		display_group = 11,
		operation_stop_id = 826,
		cost_id = {}
	},
	[29] = {
		refresh_num_limit = 0,
		initiative_refresh = 0,
		group_name = "强音收束仪",
		type = 3,
		system = "shop",
		show_in_shop = 0,
		chain_last_visible = 0,
		display_index = 1,
		activity_id = 91462,
		remark = "强音收束仪",
		params = "",
		id = 29,
		display_group = 10,
		operation_stop_id = 827,
		cost_id = {
			53006
		}
	},
	[30] = {
		refresh_num_limit = 0,
		initiative_refresh = 0,
		group_name = "样品解析站",
		type = 3,
		system = "shop",
		show_in_shop = 0,
		chain_last_visible = 0,
		display_index = 2,
		activity_id = 91461,
		remark = "样品解析站",
		params = "",
		id = 30,
		display_group = 10,
		operation_stop_id = 828,
		cost_id = {
			53007
		}
	},
	[31] = {
		refresh_num_limit = 0,
		initiative_refresh = 0,
		group_name = "情报终端",
		type = 3,
		system = "shop",
		show_in_shop = 0,
		chain_last_visible = 0,
		display_index = 1,
		activity_id = 101461,
		remark = "情报终端",
		params = "",
		id = 31,
		display_group = 10,
		operation_stop_id = 829,
		cost_id = {
			53011
		}
	},
	[32] = {
		refresh_num_limit = 0,
		initiative_refresh = 0,
		group_name = "琳琅商行",
		type = 3,
		system = "shop",
		show_in_shop = 0,
		chain_last_visible = 0,
		display_index = 1,
		activity_id = 111461,
		remark = "琳琅商行",
		params = "",
		id = 32,
		display_group = 10,
		operation_stop_id = 830,
		cost_id = {
			53012
		}
	},
	[33] = {
		refresh_num_limit = 0,
		initiative_refresh = 0,
		group_name = "战略储藏室",
		type = 3,
		system = "shop",
		show_in_shop = 0,
		chain_last_visible = 0,
		display_index = 1,
		activity_id = 121461,
		remark = "战略储藏室",
		params = "",
		id = 33,
		display_group = 10,
		operation_stop_id = 831,
		cost_id = {
			53013
		}
	},
	[35] = {
		refresh_num_limit = 0,
		initiative_refresh = 0,
		group_name = "餐厅商店",
		type = 1,
		system = "shop",
		show_in_shop = 0,
		chain_last_visible = 0,
		display_index = 1,
		activity_id = 0,
		remark = "餐厅商店",
		params = "",
		id = 35,
		display_group = 12,
		operation_stop_id = 833,
		cost_id = {
			39
		}
	},
	[36] = {
		refresh_num_limit = 0,
		initiative_refresh = 0,
		group_name = "置换中心",
		type = 3,
		system = "shop",
		show_in_shop = 0,
		chain_last_visible = 0,
		display_index = 1,
		activity_id = 131461,
		remark = "塔列朗贸易所",
		params = "",
		id = 36,
		display_group = 10,
		operation_stop_id = 834,
		cost_id = {
			53016
		}
	},
	[37] = {
		refresh_num_limit = 0,
		initiative_refresh = 0,
		group_name = "置换中心",
		type = 3,
		system = "shop",
		show_in_shop = 0,
		chain_last_visible = 0,
		display_index = 1,
		activity_id = 141951,
		remark = "天禄商号",
		params = "",
		id = 37,
		display_group = 10,
		operation_stop_id = 835,
		cost_id = {
			53017,
			54014,
			1
		}
	},
	[38] = {
		refresh_num_limit = 0,
		initiative_refresh = 0,
		group_name = "置换中心",
		type = 3,
		system = "shop",
		show_in_shop = 0,
		chain_last_visible = 0,
		display_index = 1,
		activity_id = 151461,
		remark = "猫咪黑市",
		params = "",
		id = 38,
		display_group = 10,
		operation_stop_id = 836,
		cost_id = {
			53021
		}
	},
	[39] = {
		refresh_num_limit = 0,
		initiative_refresh = 0,
		group_name = "置换中心",
		type = 1,
		system = "shop",
		show_in_shop = 0,
		chain_last_visible = 0,
		display_index = 1,
		activity_id = 142063,
		remark = "玲珑瑰藏",
		params = "",
		id = 39,
		display_group = 10,
		operation_stop_id = 837,
		cost_id = {
			53022
		}
	},
	[40] = {
		refresh_num_limit = 0,
		initiative_refresh = 0,
		group_name = "同调轨迹",
		type = 3,
		system = "shop",
		show_in_shop = 1,
		chain_last_visible = 0,
		display_index = 1,
		activity_id = 0,
		remark = "同调轨迹",
		params = "",
		id = 40,
		display_group = 13,
		operation_stop_id = 0,
		cost_id = {
			41601
		}
	},
	[41] = {
		refresh_num_limit = 0,
		initiative_refresh = 0,
		group_name = "凭证置换",
		type = 1,
		system = "shop",
		show_in_shop = 1,
		chain_last_visible = 0,
		display_index = 2,
		activity_id = 0,
		remark = "多维变量",
		params = "",
		id = 41,
		display_group = 5,
		operation_stop_id = 818,
		cost_id = {
			"CURRENCY_TYPE_MATRIX_CERTIFICATION"
		}
	},
	[2001] = {
		refresh_num_limit = 0,
		initiative_refresh = 0,
		group_name = "心居套装",
		type = 1,
		system = "shop",
		show_in_shop = 0,
		chain_last_visible = 0,
		display_index = 2,
		activity_id = 0,
		remark = "心居套装",
		params = "",
		id = 2001,
		display_group = 7,
		operation_stop_id = 835,
		cost_id = {
			"CURRENCY_TYPE_DORM_GOLD",
			"CURRENCY_TYPE_DIAMOND"
		}
	},
	[2002] = {
		refresh_num_limit = 0,
		initiative_refresh = 0,
		group_name = "雾隐洞天",
		type = 1,
		system = "shop",
		show_in_shop = 0,
		chain_last_visible = 0,
		display_index = 3,
		activity_id = 0,
		remark = "雾隐洞天",
		params = "",
		id = 2002,
		display_group = 7,
		operation_stop_id = 835,
		cost_id = {
			"CURRENCY_TYPE_DORM_GOLD",
			"CURRENCY_TYPE_DIAMOND"
		}
	},
	get_id_list_by_system = {
		recharge = {
			14,
			15,
			16,
			18,
			22,
			23
		},
		shop = {
			2,
			3,
			5,
			6,
			7,
			8,
			11,
			12,
			17,
			19,
			34,
			20,
			21,
			24,
			25,
			26,
			27,
			28,
			29,
			30,
			31,
			32,
			33,
			35,
			36,
			37,
			38,
			39,
			40,
			41,
			2001,
			2002
		}
	},
	all = {
		2,
		3,
		5,
		6,
		7,
		8,
		11,
		12,
		14,
		15,
		16,
		17,
		18,
		19,
		34,
		20,
		21,
		22,
		23,
		24,
		25,
		26,
		27,
		28,
		29,
		30,
		31,
		32,
		33,
		35,
		36,
		37,
		38,
		39,
		40,
		41,
		2001,
		2002
	}
}
