REFRESH_CLOCK = 18000
POP_ITEM = 1
POP_SOURCE_ITEM = 2
POP_OPERATE_ITEM = 3
POP_MERGE_ITEM = 4
POP_OTHER_ITEM = 5
POP_SOURCE_DES_ITEM = 6
SDK_PLATFORM = {
	YONGSHI = 1,
	DEV = 0
}
FIRST_TEST = true
SERVER_REGION = {
	USA = "en",
	JAPAN = "jp",
	CHINA = "zh_cn"
}
