require("manager/manager")

StreamConnection = require("manager/net/StreamConnection")
ReconnectLogic = require("manager/net/ReconnectLogic")
DatagramConnection = require("manager/net/DatagramConnection")
ConnectionHelper = require("manager/net/ConnectionHelper")
Protocol = require("manager/net/Protocol")
NetManager = require("manager/NetManager")
UIManager = require("manager/UIManager")
GCManager = require("manager/GCManager")
TipsMgr = require("manager/tips/TipsMgr")
TimeMgr = require("manager/TimeMgr")
ReduxFactory = require("manager/ReduxFactory")
LoadUIMgr = require("manager/LoadUIMgr")
ShowMessageMgr = require("manager/message/ShowMessageMgr")
ShowTransitionMgr = require("manager/transition/ShowTransitionMgr")
EffectMgr = require("manager/EffectMgr")
SDKSendMessageMgr = require("game/tools/SDKSendMessageMgr")
StoryHandler = require("manager/story/StoryHandler")
StoryCallback = require("manager/story/StoryCallback")
StoryPlayer = require("manager/story/StoryPlayer2")
StoryOperDefine = require("manager/story/StoryOperDefine")
StoryMgr = require("manager/StoryMgr")
AudioMgr = require("manager/AudioMgr")
InputWindowMgr = require("manager/InputWindowMgr")
WindowBarMgr = require("manager/windowBar/WindowBarMgr")
NotificationCenter = require("manager/NotificationCenter")
RedPointMgr = require("manager/RedPointMgr")
LoadSceneMgr = require("manager/LoadSceneMgr")
MatrixPopMgr = require("manager/MatrixPopMgr")
AchievementTipsMgr = require("manager/tips/achievementTips/AchievementTipsMgr")
ShareMgr = require("manager/share/ShareMgr")

require("manager/guide/includeGuide")

VideoPlayMgr = require("manager/video/VideoPlayMgr")
