ActivityInfinityPoolRewardPreviewBaseItem = import("game.views.activity.Submodule.infinityTask.base.rewardPreview.ActivityInfinityPoolRewardPreviewBaseItem")

return class("OsirisRewardPreviewItem", ActivityInfinityPoolRewardPreviewBaseItem)
