return {
	USER_ITEM_TYPE_MATERIAL = 6,
	USER_ITEM_TYPE_EQUIP_PIECE = 5,
	USER_ITEM_TYPE_DROP_GROUP = 12,
	USER_ITEM_TYPE_ACTIVITY_PT = 11,
	USER_ITEM_TYPE_CURRENCY = 1,
	USER_ITEM_TYPE_PLOT = 7,
	USER_ITEM_TYPE_HERO_PIECE = 3,
	USER_ITEM_TYPE_EQUIP_SUIT = 8,
	USER_ITEM_TYPE_BUFF = 10,
	USER_ITEM_TYPE_PASS = 9,
	USER_ITEM_TYPE_HERO = 2,
	USER_ITEM_TYPE_EQUIP = 4
}
