return {
	{
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 10,
		id = 1,
		name = "强攻",
		upgrade = 40,
		type_inner = 3,
		desc = "攻击力提高%.2f%%",
		skill_type = 0,
		lvmax = 8,
		desc_no_value = "提高攻击力",
		icon = "icon_id1",
		attribute = 11
	},
	{
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 10,
		id = 2,
		name = "狂暴",
		upgrade = 40,
		type_inner = 3,
		desc = "会心率提高%.2f%%",
		skill_type = 0,
		lvmax = 8,
		desc_no_value = "提高会心率",
		icon = "icon_id2",
		attribute = 81
	},
	{
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 10,
		id = 3,
		name = "狂怒",
		upgrade = 80,
		type_inner = 3,
		desc = "会心伤害提高%.2f%%",
		skill_type = 0,
		lvmax = 8,
		desc_no_value = "提高会心伤害",
		icon = "icon_id3",
		attribute = 82
	},
	[5] = {
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 10,
		id = 5,
		name = "胜强",
		upgrade = 25,
		type_inner = 3,
		desc = "对精英和首领敌人命中瞬间伤害提高%.2f%%",
		skill_type = 0,
		lvmax = 8,
		desc_no_value = "对精英和BOSS级别的敌人造成的伤害提高",
		icon = "icon_id5",
		attribute = 222
	},
	[6] = {
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 10,
		id = 6,
		name = "虹吸",
		upgrade = 50,
		type_inner = 0,
		desc = "能量获得率提高%.2f%%",
		skill_type = 0,
		lvmax = 4,
		desc_no_value = "能量获取量增加",
		icon = "icon_id6",
		attribute = 1103
	},
	[7] = {
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 10,
		id = 7,
		name = "修正强化",
		upgrade = 50,
		type_inner = 0,
		desc = "修正系数提高%.2f%%",
		skill_type = 0,
		lvmax = 4,
		desc_no_value = "对敌人造成修正值提高",
		icon = "icon_id7",
		attribute = 1105
	},
	[8] = {
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 10,
		id = 8,
		name = "坚守",
		upgrade = 40,
		type_inner = 1,
		desc = "防御力提高%.2f%%",
		skill_type = 0,
		lvmax = 8,
		desc_no_value = "提高防御值",
		icon = "icon_id8",
		attribute = 21
	},
	[9] = {
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 10,
		id = 9,
		name = "坚韧意志",
		upgrade = 80,
		type_inner = 1,
		desc = "生命值上限提高%.2f%%",
		skill_type = 0,
		lvmax = 8,
		desc_no_value = "提高最大生命值",
		icon = "icon_id9",
		attribute = 31
	},
	[11] = {
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 10,
		id = 11,
		name = "警戒",
		upgrade = 25,
		type_inner = 1,
		desc = "受到来自精英和首领敌人的伤害降低%.2f%%",
		skill_type = 0,
		lvmax = 6,
		desc_no_value = "使受到来自精英和BOSS级别敌人的伤害降低",
		icon = "icon_id11",
		attribute = 522
	},
	[12] = {
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 10,
		id = 12,
		name = "白刃",
		upgrade = 25,
		type_inner = 2,
		desc = "物理伤害提高%.2f%%",
		skill_type = 0,
		lvmax = 6,
		desc_no_value = "所有物理属性的伤害提高",
		icon = "icon_id12",
		attribute = 151
	},
	[13] = {
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 10,
		id = 13,
		name = "风之祈佑",
		upgrade = 25,
		type_inner = 2,
		desc = "风属性伤害提高%.2f%%",
		skill_type = 0,
		lvmax = 6,
		desc_no_value = "所有风属性的伤害提高",
		icon = "icon_id13",
		attribute = 152
	},
	[14] = {
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 10,
		id = 14,
		name = "炎之祈佑",
		upgrade = 25,
		type_inner = 2,
		desc = "火属性伤害提高%.2f%%",
		skill_type = 0,
		lvmax = 6,
		desc_no_value = "所有火属性的伤害提高",
		icon = "icon_id14",
		attribute = 153
	},
	[15] = {
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 10,
		id = 15,
		name = "雷之祈佑",
		upgrade = 25,
		type_inner = 2,
		desc = "雷属性伤害提高%.2f%%",
		skill_type = 0,
		lvmax = 6,
		desc_no_value = "所有雷属性的伤害提高",
		icon = "icon_id15",
		attribute = 158
	},
	[16] = {
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 10,
		id = 16,
		name = "暗之祈佑",
		upgrade = 25,
		type_inner = 2,
		desc = "暗属性伤害提高%.2f%%",
		skill_type = 0,
		lvmax = 6,
		desc_no_value = "所有暗属性的伤害提高",
		icon = "icon_id16",
		attribute = 156
	},
	[17] = {
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 10,
		id = 17,
		name = "光之祈佑",
		upgrade = 25,
		type_inner = 2,
		desc = "光属性伤害提高%.2f%%",
		skill_type = 0,
		lvmax = 6,
		desc_no_value = "所有光属性的伤害提高",
		icon = "icon_id17",
		attribute = 157
	},
	[18] = {
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 10,
		id = 18,
		name = "冰之祈佑",
		upgrade = 25,
		type_inner = 2,
		desc = "冰属性伤害提高%.2f%%",
		skill_type = 0,
		lvmax = 6,
		desc_no_value = "所有冰属性的伤害提高",
		icon = "icon_id18",
		attribute = 154
	},
	[19] = {
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 10,
		id = 19,
		name = "雨之祈佑",
		upgrade = 25,
		type_inner = 2,
		desc = "水属性伤害提高%.2f%%",
		skill_type = 0,
		lvmax = 6,
		desc_no_value = "所有水属性的伤害提高",
		icon = "icon_id19",
		attribute = 155
	},
	[20] = {
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 10,
		id = 20,
		name = "对兵战术",
		upgrade = 25,
		type_inner = 2,
		desc = "对人形敌人伤害提高%.2f%%",
		skill_type = 0,
		lvmax = 4,
		desc_no_value = "对人形类型的怪物伤害提高",
		icon = "icon_id20",
		attribute = 201
	},
	[21] = {
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 10,
		id = 21,
		name = "对钢战术",
		upgrade = 25,
		type_inner = 2,
		desc = "对智械敌人伤害提高%.2f%%",
		skill_type = 0,
		lvmax = 4,
		desc_no_value = "对智械类型的怪物伤害提高",
		icon = "icon_id21",
		attribute = 202
	},
	[22] = {
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 10,
		id = 22,
		name = "对骸战术",
		upgrade = 25,
		type_inner = 2,
		desc = "对视骸敌人伤害提高%.2f%%",
		skill_type = 0,
		lvmax = 4,
		desc_no_value = "对视骸类型的怪物伤害提高",
		icon = "icon_id22",
		attribute = 203
	},
	[23] = {
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 10,
		id = 23,
		name = "狂澜怒涛",
		upgrade = 50,
		type_inner = 0,
		desc = "怒气获得率提高%.2f%%",
		skill_type = 0,
		lvmax = 4,
		desc_no_value = "怒气获取量增加",
		icon = "icon_id23",
		attribute = 1102
	},
	[25] = {
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 10,
		id = 25,
		name = "御兵之盾",
		upgrade = 25,
		type_inner = 1,
		desc = "受到来自人形敌人的伤害降低%.2f%%",
		skill_type = 0,
		lvmax = 6,
		desc_no_value = "受到来自人形类型怪物的伤害降低",
		icon = "icon_id25",
		attribute = 511
	},
	[26] = {
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 10,
		id = 26,
		name = "御钢之盾",
		upgrade = 25,
		type_inner = 1,
		desc = "受到来自智械敌人的伤害降低%.2f%%",
		skill_type = 0,
		lvmax = 6,
		desc_no_value = "受到来自智械类型怪物的伤害降低",
		icon = "icon_id26",
		attribute = 512
	},
	[27] = {
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 10,
		id = 27,
		name = "御骸之盾",
		upgrade = 25,
		type_inner = 1,
		desc = "受到来自视骸敌人的伤害降低%.2f%%",
		skill_type = 0,
		lvmax = 6,
		desc_no_value = "受到来自视骸类型怪物的伤害降低",
		icon = "icon_id27",
		attribute = 513
	},
	[28] = {
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 10,
		id = 28,
		name = "心流",
		upgrade = 100,
		type_inner = 3,
		desc = "奥义伤害提高%.2f%%",
		skill_type = 0,
		lvmax = 4,
		desc_no_value = "奥义的伤害提高",
		icon = "icon_id28",
		attribute = 303
	},
	[29] = {
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 10,
		id = 29,
		name = "回环",
		upgrade = 50,
		type_inner = 0,
		desc = "奥义获得率提高%.2f%%",
		skill_type = 0,
		lvmax = 4,
		desc_no_value = "奥义充能增加",
		icon = "icon_id29",
		attribute = 1101
	},
	[30] = {
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 10,
		id = 30,
		name = "灵动",
		upgrade = 50,
		type_inner = 0,
		desc = "闪避值消耗降低%.2f%%",
		skill_type = 0,
		lvmax = 4,
		desc_no_value = "闪避消耗的闪避能量减少",
		icon = "icon_id30",
		attribute = 1002
	},
	[31] = {
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 10,
		id = 31,
		name = "连锁强化",
		upgrade = 50,
		type_inner = 0,
		desc = "评分值获得率提高%.2f%%",
		skill_type = 0,
		lvmax = 4,
		desc_no_value = "评分值的获取速度提高",
		icon = "icon_id31",
		attribute = 1106
	},
	[32] = {
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 1000,
		id = 32,
		name = "零时敏锐",
		upgrade = 1000,
		type_inner = 0,
		desc = "闪避效果的冷却时间缩短%.2f秒",
		skill_type = 0,
		lvmax = 2,
		desc_no_value = "触发闪避效果的冷却时间缩短",
		icon = "icon_id32",
		attribute = 1005
	},
	[33] = {
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 10,
		id = 33,
		name = "圣体",
		upgrade = 50,
		type_inner = 1,
		desc = "受到的治疗效果提高%.2f%%",
		skill_type = 0,
		lvmax = 4,
		desc_no_value = "受到的治疗效果提高",
		icon = "icon_id33",
		attribute = 44
	},
	[34] = {
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 10,
		id = 34,
		name = "蓄势待发",
		upgrade = 100,
		type_inner = 2,
		desc = "蓄力技能伤害提高%.2f%%",
		skill_type = 0,
		lvmax = 4,
		desc_no_value = "蓄力类型的技能伤害提高",
		icon = "icon_id34",
		attribute = 315
	},
	[35] = {
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 10,
		id = 35,
		name = "斗士",
		upgrade = 100,
		type_inner = 3,
		desc = "普通攻击伤害提高%.2f%%",
		skill_type = 0,
		lvmax = 4,
		desc_no_value = "普通攻击的伤害提高",
		icon = "icon_id35",
		attribute = 301
	},
	[36] = {
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 10,
		id = 36,
		name = "战术强化",
		upgrade = 25,
		type_inner = 3,
		desc = "技能伤害提高%.2f%%",
		skill_type = 0,
		lvmax = 8,
		desc_no_value = "技能类型的伤害提高",
		icon = "icon_id36",
		attribute = 302
	},
	[41] = {
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 10,
		id = 41,
		name = "瞬步",
		upgrade = 100,
		type_inner = 0,
		desc = "闪避值上限%.2f%%",
		skill_type = 0,
		lvmax = 3,
		desc_no_value = "闪避能量上限增加",
		icon = "icon_id41",
		attribute = 1004
	},
	[42] = {
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 10,
		id = 42,
		name = "余息",
		upgrade = 100,
		type_inner = 0,
		desc = "闪避值恢复速度提高%.2f%%",
		skill_type = 0,
		lvmax = 3,
		desc_no_value = "闪避的回复速度增加",
		icon = "icon_id42",
		attribute = 1003
	},
	[43] = {
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 10,
		id = 43,
		name = "意志",
		upgrade = 50,
		type_inner = 0,
		desc = "怒气消耗降低%.2f%%",
		skill_type = 0,
		lvmax = 4,
		desc_no_value = "怒气技能的消耗降低",
		icon = "icon_id43",
		attribute = 1109
	},
	[44] = {
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 10,
		id = 44,
		name = "精密储备",
		upgrade = 50,
		type_inner = 0,
		desc = "能量消耗降低%.2f%%",
		skill_type = 0,
		lvmax = 4,
		desc_no_value = "能量技能的消耗降低",
		icon = "icon_id44",
		attribute = 1110
	},
	[46] = {
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 10,
		id = 46,
		name = "灵性疗愈",
		upgrade = 50,
		type_inner = 1,
		desc = "治疗效果提高%.2f%%",
		skill_type = 0,
		lvmax = 4,
		desc_no_value = "造成治疗效果增加",
		icon = "icon_id46",
		attribute = 42
	},
	[47] = {
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 10,
		id = 47,
		name = "无双",
		upgrade = 50,
		type_inner = 2,
		desc = "对普通敌人命中瞬间伤害提高%.2f%%",
		skill_type = 0,
		lvmax = 4,
		desc_no_value = "对小怪类型伤害增加",
		icon = "icon_id47",
		attribute = 221
	},
	[48] = {
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 10,
		id = 48,
		name = "刚毅",
		upgrade = 25,
		type_inner = 1,
		desc = "受到的伤害降低%.2f%%",
		skill_type = 0,
		lvmax = 4,
		desc_no_value = "受到伤害降低",
		icon = "icon_id48",
		attribute = 500
	},
	[101] = {
		desc_spec_value = "",
		equip_effect_id = 101,
		percent = 10,
		id = 101,
		name = "强化因子·近战",
		upgrade = 20,
		type_inner = 999,
		desc = "近战伤害提高<color=#ED6117>%s</color>",
		skill_type = 1,
		lvmax = 3,
		desc_no_value = "近战伤害提高",
		icon = "icon_id101",
		attribute = 101
	},
	[102] = {
		desc_spec_value = "",
		equip_effect_id = 101,
		percent = 10,
		id = 102,
		name = "强化因子·远程",
		upgrade = 20,
		type_inner = 999,
		desc = "远程伤害提高<color=#ED6117>%s</color>",
		skill_type = 1,
		lvmax = 3,
		desc_no_value = "远程伤害提高",
		icon = "icon_id102",
		attribute = 102
	},
	[103] = {
		desc_spec_value = "",
		equip_effect_id = 103,
		percent = 10,
		id = 103,
		name = "突变磁场",
		upgrade = 40,
		type_inner = 999,
		desc = "生命值越多命中瞬间伤害越高，最高<color=#ED6117>%s</color>",
		skill_type = 1,
		lvmax = 3,
		desc_no_value = "角色生命值越多伤害越高",
		icon = "icon_id103",
		attribute = 401
	},
	[104] = {
		desc_spec_value = "",
		equip_effect_id = 104,
		percent = 10,
		id = 104,
		name = "喋血支配",
		upgrade = 120,
		type_inner = 999,
		desc = "生命值越少命中瞬间伤害越高，最高<color=#ED6117>%s</color>",
		skill_type = 1,
		lvmax = 3,
		desc_no_value = "角色生命值越少伤害越高",
		icon = "icon_id104",
		attribute = 401
	},
	[105] = {
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 1,
		id = 105,
		name = "精密中枢",
		upgrade = 2,
		type_inner = 999,
		desc = "普通攻击等级提高<color=#ED6117>%s</color>级",
		skill_type = 1,
		lvmax = 3,
		desc_no_value = "角色普攻等级提高",
		icon = "icon_id105",
		attribute = 0
	},
	[106] = {
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 1,
		id = 106,
		name = "演化颗粒Ⅰ",
		upgrade = 2,
		type_inner = 999,
		desc = "技能一等级提高<color=#ED6117>%s</color>级",
		skill_type = 1,
		lvmax = 3,
		desc_no_value = "角色1技能等级提高",
		icon = "icon_id106",
		attribute = 0
	},
	[107] = {
		desc_spec_value = "",
		equip_effect_id = 107,
		percent = 10,
		id = 107,
		name = "念动矢量Ⅰ",
		upgrade = 25,
		type_inner = 999,
		desc = "技能一基础伤害提高<color=#ED6117>%s</color>",
		skill_type = 1,
		lvmax = 3,
		desc_no_value = "角色1技能的基础伤害提高",
		icon = "icon_id107",
		attribute = 51
	},
	[108] = {
		desc_spec_value = "",
		equip_effect_id = 108,
		percent = 10,
		id = 108,
		name = "闪回核心Ⅰ",
		upgrade = 20,
		type_inner = 999,
		desc = "技能一的冷却时间缩短<color=#ED6117>%s</color>",
		skill_type = 1,
		lvmax = 3,
		desc_no_value = "角色1技能的CD缩短",
		icon = "icon_id108",
		attribute = 0
	},
	[109] = {
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 1,
		id = 109,
		name = "演化颗粒Ⅱ",
		upgrade = 2,
		type_inner = 999,
		desc = "技能二等级提高<color=#ED6117>%s</color>级",
		skill_type = 1,
		lvmax = 3,
		desc_no_value = "角色2技能等级提高",
		icon = "icon_id109",
		attribute = 0
	},
	[110] = {
		desc_spec_value = "",
		equip_effect_id = 107,
		percent = 10,
		id = 110,
		name = "念动矢量Ⅱ",
		upgrade = 25,
		type_inner = 999,
		desc = "技能二基础伤害提高<color=#ED6117>%s</color>",
		skill_type = 1,
		lvmax = 3,
		desc_no_value = "角色2技能的基础伤害提高",
		icon = "icon_id110",
		attribute = 52
	},
	[111] = {
		desc_spec_value = "",
		equip_effect_id = 111,
		percent = 10,
		id = 111,
		name = "闪回核心Ⅱ",
		upgrade = 20,
		type_inner = 999,
		desc = "技能二的冷却时间缩短<color=#ED6117>%s</color>",
		skill_type = 1,
		lvmax = 3,
		desc_no_value = "角色2技能的CD缩短",
		icon = "icon_id111",
		attribute = 0
	},
	[112] = {
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 1,
		id = 112,
		name = "演化颗粒Ⅲ",
		upgrade = 2,
		type_inner = 999,
		desc = "技能三等级提高<color=#ED6117>%s</color>级",
		skill_type = 1,
		lvmax = 3,
		desc_no_value = "角色3技能等级提高",
		icon = "icon_id112",
		attribute = 0
	},
	[113] = {
		desc_spec_value = "",
		equip_effect_id = 107,
		percent = 10,
		id = 113,
		name = "念动矢量Ⅲ",
		upgrade = 25,
		type_inner = 999,
		desc = "技能三基础伤害提高<color=#ED6117>%s</color>",
		skill_type = 1,
		lvmax = 3,
		desc_no_value = "角色3技能的基础伤害提高",
		icon = "icon_id113",
		attribute = 53
	},
	[114] = {
		desc_spec_value = "",
		equip_effect_id = 114,
		percent = 10,
		id = 114,
		name = "闪回核心Ⅲ",
		upgrade = 20,
		type_inner = 999,
		desc = "技能三的冷却时间缩短<color=#ED6117>%s</color>",
		skill_type = 1,
		lvmax = 3,
		desc_no_value = "角色3技能的CD缩短",
		icon = "icon_id114",
		attribute = 0
	},
	[115] = {
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 1,
		id = 115,
		name = "演化颗粒Ⅳ",
		upgrade = 2,
		type_inner = 999,
		desc = "技能四等级提高<color=#ED6117>%s</color>级",
		skill_type = 1,
		lvmax = 3,
		desc_no_value = "角色4技能等级提高",
		icon = "icon_id115",
		attribute = 0
	},
	[116] = {
		desc_spec_value = "",
		equip_effect_id = 107,
		percent = 10,
		id = 116,
		name = "念动矢量Ⅳ",
		upgrade = 25,
		type_inner = 999,
		desc = "技能四基础伤害提高<color=#ED6117>%s</color>",
		skill_type = 1,
		lvmax = 3,
		desc_no_value = "角色4技能的基础伤害提高",
		icon = "icon_id116",
		attribute = 54
	},
	[117] = {
		desc_spec_value = "",
		equip_effect_id = 117,
		percent = 10,
		id = 117,
		name = "null",
		upgrade = 20,
		type_inner = 999,
		desc = "null",
		skill_type = 1,
		lvmax = 3,
		desc_no_value = "null",
		icon = "icon_id117",
		attribute = 0
	},
	[118] = {
		desc_spec_value = "",
		equip_effect_id = 0,
		percent = 1,
		id = 118,
		name = "迭代感知",
		upgrade = 2,
		type_inner = 999,
		desc = "奥义等级提高<color=#ED6117>%s</color>级",
		skill_type = 1,
		lvmax = 3,
		desc_no_value = "角色奥义等级提高",
		icon = "icon_id118",
		attribute = 0
	},
	[119] = {
		desc_spec_value = "",
		equip_effect_id = 119,
		percent = 10,
		id = 119,
		name = "奥术方程",
		upgrade = 150,
		type_inner = 999,
		desc = "自身的连携奥义伤害提高<color=#ED6117>%s</color>",
		skill_type = 1,
		lvmax = 3,
		desc_no_value = "角色连携奥义伤害提高",
		icon = "icon_id119",
		attribute = 303
	},
	[120] = {
		desc_spec_value = "",
		equip_effect_id = 120,
		percent = 10,
		id = 120,
		name = "扩散钟摆",
		upgrade = 15,
		type_inner = 999,
		desc = "奥义冷却时间缩短<color=#ED6117>%s</color>",
		skill_type = 1,
		lvmax = 3,
		desc_no_value = "角色奥义的CD缩短",
		icon = "icon_id120",
		attribute = 0
	},
	[121] = {
		desc_spec_value = "",
		equip_effect_id = 121,
		percent = 10,
		id = 121,
		name = "唤灵力场Ⅰ",
		upgrade = 25,
		type_inner = 999,
		desc = "神格第三层任意1个效果激活时，伤害提高<color=#ED6117>%s</color>",
		skill_type = 1,
		lvmax = 3,
		desc_no_value = "神格第三层效果激活时伤害提高",
		icon = "icon_id121",
		attribute = 401
	},
	[122] = {
		desc_spec_value = "",
		equip_effect_id = 122,
		percent = 10,
		id = 122,
		name = "唤灵力场Ⅱ",
		upgrade = 30,
		type_inner = 999,
		desc = "神格第一层仅有2个效果激活时，伤害提高<color=#ED6117>%s</color>",
		skill_type = 1,
		lvmax = 3,
		desc_no_value = "角色仅2个神格第一层效果激活时伤害提高",
		icon = "icon_id122",
		attribute = 401
	},
	[123] = {
		desc_spec_value = "",
		equip_effect_id = 123,
		percent = 10,
		id = 123,
		name = "唤灵力场Ⅲ",
		upgrade = 35,
		type_inner = 999,
		desc = "神格第一层3个效果都激活时，伤害提高<color=#ED6117>%s</color>",
		skill_type = 1,
		lvmax = 3,
		desc_no_value = "角色3个神格第一层效果都激活时伤害提高",
		icon = "icon_id123",
		attribute = 401
	},
	[124] = {
		desc_spec_value = "",
		equip_effect_id = 124,
		percent = 10,
		id = 124,
		name = "审判官",
		upgrade = 65,
		type_inner = 999,
		desc = "对生命值高于85%%的敌人命中瞬间伤害提高<color=#ED6117>%s</color>",
		skill_type = 1,
		lvmax = 3,
		desc_no_value = "对生命值高于85%的敌人伤害提高",
		icon = "icon_id124",
		attribute = 401
	},
	[125] = {
		desc_spec_value = "",
		equip_effect_id = 125,
		percent = 10,
		id = 125,
		name = "处刑者",
		upgrade = 30,
		type_inner = 999,
		desc = "对生命值低于40%%的敌人命中瞬间伤害提高<color=#ED6117>%s</color>",
		skill_type = 1,
		lvmax = 3,
		desc_no_value = "对生命值低于40%的敌人伤害提高",
		icon = "icon_id125",
		attribute = 401
	},
	[126] = {
		desc_spec_value = "",
		equip_effect_id = 126,
		percent = 10,
		id = 126,
		name = "破甲兵装",
		upgrade = 25,
		type_inner = 999,
		desc = "对处于虚弱、破甲的敌人伤害提高<color=#ED6117>%s</color>",
		skill_type = 1,
		lvmax = 3,
		desc_no_value = "对处于虚弱、破甲的敌人伤害提高",
		icon = "icon_id126",
		attribute = 401
	},
	[127] = {
		desc_spec_value = "",
		equip_effect_id = 127,
		percent = 10,
		id = 127,
		name = "以太眩击",
		upgrade = 30,
		type_inner = 999,
		desc = "对处于部分异常状态的敌人伤害提高<color=#ED6117>%s</color>\n部分异常状态包括：受创，灼烧，眩晕，冰冻，禁锢，混乱。",
		skill_type = 1,
		lvmax = 3,
		desc_no_value = "对处于异常状态的敌人伤害提高",
		icon = "icon_id127",
		attribute = 401
	},
	[128] = {
		desc_spec_value = "",
		equip_effect_id = 128,
		percent = 10,
		id = 128,
		name = "涡电瓦解",
		upgrade = 35,
		type_inner = 999,
		desc = "对处于控制抗性的敌人伤害提高<color=#ED6117>%s</color>",
		skill_type = 1,
		lvmax = 3,
		desc_no_value = "对处于控制抗性的敌人伤害提高",
		icon = "icon_id128",
		attribute = 401
	},
	[129] = {
		desc_spec_value = "",
		equip_effect_id = 129,
		percent = 10,
		id = 129,
		name = "绝对零度",
		upgrade = 40,
		type_inner = 999,
		desc = "处于零时空间时，伤害提高<color=#ED6117>%s</color>",
		skill_type = 1,
		lvmax = 3,
		desc_no_value = "处于零时空间时伤害提高",
		icon = "icon_id129",
		attribute = 401
	},
	[130] = {
		desc_spec_value = "",
		equip_effect_id = 130,
		percent = 10,
		id = 130,
		name = "动能修正",
		upgrade = 75,
		type_inner = 999,
		desc = "处于修正模式时，伤害提高<color=#ED6117>%s</color>",
		skill_type = 1,
		lvmax = 3,
		desc_no_value = "处于修正模式时伤害提高",
		icon = "icon_id130",
		attribute = 421
	},
	[131] = {
		desc_spec_value = "",
		equip_effect_id = 131,
		percent = 10,
		id = 131,
		name = "势能聚变",
		upgrade = 40,
		type_inner = 999,
		desc = "自身处于持续伤害状态或生命移除状态时，伤害提高<color=#ED6117>%s</color>",
		skill_type = 1,
		lvmax = 3,
		desc_no_value = "处于持续伤害状态时伤害提高",
		icon = "icon_id131",
		attribute = 401
	},
	[132] = {
		desc_spec_value = "",
		equip_effect_id = 131,
		percent = 10,
		id = 132,
		name = "波谷干涉",
		upgrade = 50,
		type_inner = 999,
		desc = "自身处于持续伤害状态或生命移除状态时，受到伤害降低<color=#ED6117>%s</color>",
		skill_type = 1,
		lvmax = 3,
		desc_no_value = "处于持续伤害状态时受到伤害降低",
		icon = "icon_id132",
		attribute = 500
	},
	[133] = {
		desc_spec_value = "",
		equip_effect_id = 133,
		percent = 10,
		id = 133,
		name = "虚像瞄准",
		upgrade = 30,
		type_inner = 999,
		desc = "自身受到处于持续伤害状态的敌人的伤害降低<color=#ED6117>%s</color>",
		skill_type = 1,
		lvmax = 3,
		desc_no_value = "受到处于持续伤害状态的敌人伤害降低",
		icon = "icon_id133",
		attribute = 500
	},
	[134] = {
		desc_spec_value = "",
		equip_effect_id = 134,
		percent = 10,
		id = 134,
		name = "布朗运动",
		upgrade = 55,
		type_inner = 999,
		desc = "蓄力期间受到的伤害降低<color=#ED6117>%s</color>",
		skill_type = 1,
		lvmax = 3,
		desc_no_value = "蓄力期间受到的伤害降低",
		icon = "icon_id134",
		attribute = 500
	},
	[135] = {
		desc_spec_value = "",
		equip_effect_id = 135,
		percent = 10,
		id = 135,
		name = "凹反射镜",
		upgrade = 30,
		type_inner = 999,
		desc = "普通攻击期间受到的伤害降低<color=#ED6117>%s</color>",
		skill_type = 1,
		lvmax = 3,
		desc_no_value = "普通攻击期间受到的伤害降低",
		icon = "icon_id135",
		attribute = 500
	},
	[136] = {
		desc_spec_value = "",
		equip_effect_id = 136,
		percent = 10,
		id = 136,
		name = "绝缘装甲",
		upgrade = 70,
		type_inner = 999,
		desc = "处于部分控制效果期间受到的伤害降低<color=#ED6117>%s</color>\n部分控制效果包括：禁锢，眩晕，冰冻，石化，睡眠。",
		skill_type = 1,
		lvmax = 3,
		desc_no_value = "被控制期间受到的伤害降低",
		icon = "icon_id136",
		attribute = 500
	},
	[137] = {
		desc_spec_value = "",
		equip_effect_id = 137,
		percent = 1,
		id = 137,
		name = "怒体掌控",
		upgrade = 15,
		type_inner = 999,
		desc = "出场时，恢复<color=#ED6117>%s</color>点怒气",
		skill_type = 1,
		lvmax = 3,
		desc_no_value = "出场时获得怒气",
		icon = "icon_id137",
		attribute = 0
	},
	[138] = {
		desc_spec_value = "",
		equip_effect_id = 137,
		percent = 1,
		id = 138,
		name = "正体气囊",
		upgrade = 15,
		type_inner = 999,
		desc = "出场时，恢复<color=#ED6117>%s</color>点能量",
		skill_type = 1,
		lvmax = 3,
		desc_no_value = "出场时获得能量",
		icon = "icon_id138",
		attribute = 0
	},
	[139] = {
		desc_spec_value = "",
		equip_effect_id = 137,
		percent = 1,
		id = 139,
		name = "能力追踪",
		upgrade = 1,
		type_inner = 999,
		desc = "出场时，恢复<color=#ED6117>%s</color>个印记",
		skill_type = 1,
		lvmax = 3,
		desc_no_value = "出场时获得印记",
		icon = "icon_id139",
		attribute = 0
	},
	[140] = {
		desc_spec_value = "",
		equip_effect_id = 137,
		percent = 1,
		id = 140,
		name = "未元感知",
		upgrade = 15,
		type_inner = 999,
		desc = "出场时，恢复<color=#ED6117>%s</color>点神能",
		skill_type = 1,
		lvmax = 3,
		desc_no_value = "出场时获得神能",
		icon = "icon_id140",
		attribute = 0
	},
	[141] = {
		desc_spec_value = "",
		equip_effect_id = 141,
		percent = 1,
		id = 141,
		name = "无尽构筑",
		upgrade = 10,
		type_inner = 999,
		desc = "出场时，恢复<color=#ED6117>%s</color>的奥义值",
		skill_type = 1,
		lvmax = 3,
		desc_no_value = "出场时获得奥义充能",
		icon = "icon_id141",
		attribute = 0
	},
	[142] = {
		desc_spec_value = "",
		equip_effect_id = 142,
		percent = 10,
		id = 142,
		name = "引力势律",
		upgrade = 40,
		type_inner = 999,
		desc = "自身的生命值低于40%%时，治疗效果提高<color=#ED6117>%s</color>",
		skill_type = 1,
		lvmax = 3,
		desc_no_value = "角色生命值低于40%时治疗效果提高",
		icon = "icon_id142",
		attribute = 42
	},
	[143] = {
		desc_spec_value = "",
		equip_effect_id = 142,
		percent = 10,
		id = 143,
		name = "引力场律",
		upgrade = 40,
		type_inner = 999,
		desc = "自身的生命值低于40%%时，受到的治疗效果提高<color=#ED6117>%s</color>",
		skill_type = 1,
		lvmax = 3,
		desc_no_value = "角色生命值低于40%时受到治疗效果提高",
		icon = "icon_id143",
		attribute = 44
	},
	get_id_list_by_skill_type = {
		[0] = {
			1,
			2,
			3,
			5,
			6,
			7,
			8,
			9,
			11,
			12,
			13,
			14,
			15,
			16,
			17,
			18,
			19,
			20,
			21,
			22,
			23,
			25,
			26,
			27,
			28,
			29,
			30,
			31,
			32,
			33,
			34,
			35,
			36,
			41,
			42,
			43,
			44,
			46,
			47,
			48
		},
		{
			101,
			102,
			103,
			104,
			105,
			106,
			107,
			108,
			109,
			110,
			111,
			112,
			113,
			114,
			115,
			116,
			117,
			118,
			119,
			120,
			121,
			122,
			123,
			124,
			125,
			126,
			127,
			128,
			129,
			130,
			131,
			132,
			133,
			134,
			135,
			136,
			137,
			138,
			139,
			140,
			141,
			142,
			143
		}
	},
	all = {
		1,
		2,
		3,
		5,
		6,
		7,
		8,
		9,
		11,
		12,
		13,
		14,
		15,
		16,
		17,
		18,
		19,
		20,
		21,
		22,
		23,
		25,
		26,
		27,
		28,
		29,
		30,
		31,
		32,
		33,
		34,
		35,
		36,
		41,
		42,
		43,
		44,
		46,
		47,
		48,
		101,
		102,
		103,
		104,
		105,
		106,
		107,
		108,
		109,
		110,
		111,
		112,
		113,
		114,
		115,
		116,
		117,
		118,
		119,
		120,
		121,
		122,
		123,
		124,
		125,
		126,
		127,
		128,
		129,
		130,
		131,
		132,
		133,
		134,
		135,
		136,
		137,
		138,
		139,
		140,
		141,
		142,
		143
	}
}
