return {
	TIMING_WALK = 2,
	TIMING_START = 0,
	TIMING_ALL = 9,
	TIMING_STONE_MOVE = 7,
	BULLET = 106021,
	HOLE_GRID_ID = 20604,
	TIMING_INTERACT = 3,
	TIMING_CURRENT_HIT = 6,
	TIMING_HIT = 4,
	STONE_GRID_ID = 20601,
	TIMING_CLICK = 1,
	TIMING_CURRENT = 5,
	GLOBAL = {
		COUNT_STEP = 6,
		ORDER_EVENT = 7,
		SEAL = 9,
		TALLY = 8,
		AREA = 5,
		CHECK = 10,
		KEY = 3,
		START = 1,
		EVENT = 4,
		PROGRESS = 2
	},
	EVENT = {
		AFTER_BATTLE = "AFTER_BATTLE"
	},
	BOX = {
		BIG_GRID = 10502,
		SMALL = 10203,
		BIG = 10204,
		CLUE = 106031,
		SMALL_GRID = 10501
	},
	BULLET_MAX = WarchessObjectCfg[106021].max,
	TEMPORARY_KEY = {
		TREASURE = 1,
		DEBUFF = 2
	},
	GAME_PLAY = {
		SHIP = 2,
		FIRE_BULLET = 1
	},
	OBJECT_TYPE = {
		ENERGY = 2,
		ITEM = 1
	},
	MUTI_DATA_TYPE = {
		CHIP = 2,
		HERO = 1,
		COMBO = 3
	}
}
